#!/usr/bin/env python3
"""
Process RDA download script and organize GFS files by date.

This script:
1. Parses the download script generated by RDA's subset tool
2. Downloads files in parallel
3. Organizes them by date for preprocessing

Usage:
    # After getting the download script from RDA:
    python scripts/process_rda_download.py --rda-script download_ds084.1.py --output-dir /path/to/gfs

    # Or download using extracted URLs:
    python scripts/process_rda_download.py --url-file urls.txt --output-dir /path/to/gfs
"""

import os
import re
import sys
import argparse
import subprocess
from pathlib import Path
from concurrent.futures import ThreadPoolExecutor, as_completed
from collections import defaultdict
import logging
import requests
import time

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

# Output directory
DEFAULT_OUTPUT_DIR = '/mnt/f/STOFS_TRAINING_DATA/gfs_forcing'


def extract_urls_from_rda_script(script_path: Path) -> list:
    """
    Extract download URLs from RDA-generated Python or shell script.
    """
    urls = []

    with open(script_path, 'r') as f:
        content = f.read()

    # Pattern for Python scripts
    # Usually contains: filelist = ['url1', 'url2', ...]
    python_pattern = r"'(https?://[^']+\.grib2[^']*)'"
    matches = re.findall(python_pattern, content)
    urls.extend(matches)

    # Pattern for shell/csh scripts
    # Usually contains: wget "url"
    shell_pattern = r'wget[^"]*"(https?://[^"]+)"'
    matches = re.findall(shell_pattern, content)
    urls.extend(matches)

    # Direct URL pattern
    url_pattern = r'(https?://[^\s]+\.grib2)'
    matches = re.findall(url_pattern, content)
    urls.extend(matches)

    # Remove duplicates while preserving order
    seen = set()
    unique_urls = []
    for url in urls:
        if url not in seen:
            seen.add(url)
            unique_urls.append(url)

    return unique_urls


def parse_gfs_filename(url: str) -> dict:
    """
    Parse GFS filename to extract date and forecast hour.

    Examples:
        gfs.0p25.2023010800.f000.grib2 -> date=20230108, hour=00, fhr=000
        gfs.t00z.pgrb2.0p25.f003 -> fhr=003
    """
    filename = url.split('/')[-1]

    # Pattern 1: gfs.0p25.YYYYMMDDHH.fFFF.grib2
    match = re.search(r'gfs\.0p25\.(\d{10})\.f(\d{3})', filename)
    if match:
        datetime_str = match.group(1)
        fhr = int(match.group(2))
        return {
            'date': datetime_str[:8],
            'hour': datetime_str[8:10],
            'fhr': fhr,
            'filename': filename
        }

    # Pattern 2: gfs.tHHz.pgrb2.0p25.fFFF
    match = re.search(r'gfs\.t(\d{2})z\.pgrb2\.0p25\.f(\d{3})', filename)
    if match:
        hour = match.group(1)
        fhr = int(match.group(2))
        # Need to extract date from URL path
        date_match = re.search(r'/(\d{8})/', url)
        date = date_match.group(1) if date_match else 'unknown'
        return {
            'date': date,
            'hour': hour,
            'fhr': fhr,
            'filename': filename
        }

    return {'filename': filename}


def download_file(url: str, output_path: Path, auth: tuple = None, max_retries: int = 3) -> bool:
    """Download a single file with retries."""
    for attempt in range(max_retries):
        try:
            response = requests.get(url, stream=True, timeout=300, auth=auth)
            if response.status_code == 200:
                with open(output_path, 'wb') as f:
                    for chunk in response.iter_content(chunk_size=8192):
                        f.write(chunk)
                if output_path.exists() and output_path.stat().st_size > 1000:
                    return True
            elif response.status_code == 401:
                logger.error(f"Authentication required for {url}")
                return False
        except Exception as e:
            logger.debug(f"Attempt {attempt+1} failed for {url}: {e}")
            time.sleep(2 ** attempt)

    return False


def download_with_wget(url: str, output_path: Path, cookies_file: Path = None) -> bool:
    """Download using wget with optional cookies for authentication."""
    cmd = ['wget', '-q', '-O', str(output_path)]

    if cookies_file and cookies_file.exists():
        cmd.extend(['--load-cookies', str(cookies_file)])

    cmd.append(url)

    try:
        result = subprocess.run(cmd, timeout=300, capture_output=True)
        return result.returncode == 0 and output_path.exists() and output_path.stat().st_size > 1000
    except:
        return False


def organize_downloads(urls: list, output_dir: Path, max_workers: int = 4,
                       cookies_file: Path = None) -> dict:
    """
    Download and organize files by date.
    """
    output_dir.mkdir(parents=True, exist_ok=True)

    # Group URLs by date
    by_date = defaultdict(list)
    for url in urls:
        info = parse_gfs_filename(url)
        date = info.get('date', 'unknown')
        by_date[date].append((url, info))

    logger.info(f"Found {len(urls)} files across {len(by_date)} dates")

    results = {'success': 0, 'failed': 0, 'skipped': 0}

    for date, url_infos in sorted(by_date.items()):
        date_dir = output_dir / date
        date_dir.mkdir(exist_ok=True)

        logger.info(f"Processing {date}: {len(url_infos)} files")

        for url, info in url_infos:
            filename = info.get('filename', url.split('/')[-1])
            output_path = date_dir / filename

            if output_path.exists() and output_path.stat().st_size > 1000:
                results['skipped'] += 1
                continue

            if download_with_wget(url, output_path, cookies_file):
                results['success'] += 1
            elif download_file(url, output_path):
                results['success'] += 1
            else:
                results['failed'] += 1
                logger.warning(f"Failed: {filename}")

    return results


def create_rda_cookies(email: str, password: str, output_file: Path) -> bool:
    """
    Create cookies file for RDA authentication.
    """
    try:
        session = requests.Session()

        # Login to RDA
        login_url = 'https://rda.ucar.edu/cgi-bin/login'
        login_data = {
            'email': email,
            'passwd': password,
            'action': 'login'
        }

        response = session.post(login_url, data=login_data)

        if response.status_code == 200 and 'Authentication successful' in response.text:
            # Save cookies in Netscape format for wget
            with open(output_file, 'w') as f:
                f.write("# Netscape HTTP Cookie File\n")
                for cookie in session.cookies:
                    f.write(f"{cookie.domain}\tTRUE\t{cookie.path}\t"
                           f"{'TRUE' if cookie.secure else 'FALSE'}\t"
                           f"{cookie.expires or 0}\t{cookie.name}\t{cookie.value}\n")
            return True

    except Exception as e:
        logger.error(f"Login failed: {e}")

    return False


def main():
    parser = argparse.ArgumentParser(description='Process RDA download script')
    parser.add_argument('--rda-script', type=str, help='Path to RDA-generated download script')
    parser.add_argument('--url-file', type=str, help='File containing URLs (one per line)')
    parser.add_argument('--output-dir', type=str, default=DEFAULT_OUTPUT_DIR)
    parser.add_argument('--workers', type=int, default=4)
    parser.add_argument('--email', type=str, help='RDA email for authentication')
    parser.add_argument('--password', type=str, help='RDA password')
    args = parser.parse_args()

    output_dir = Path(args.output_dir)

    # Extract URLs
    urls = []

    if args.rda_script:
        script_path = Path(args.rda_script)
        if not script_path.exists():
            logger.error(f"Script not found: {script_path}")
            return
        urls = extract_urls_from_rda_script(script_path)
        logger.info(f"Extracted {len(urls)} URLs from {script_path}")

    elif args.url_file:
        url_file = Path(args.url_file)
        if not url_file.exists():
            logger.error(f"URL file not found: {url_file}")
            return
        with open(url_file) as f:
            urls = [line.strip() for line in f if line.strip() and line.startswith('http')]
        logger.info(f"Read {len(urls)} URLs from {url_file}")

    else:
        logger.error("Specify --rda-script or --url-file")
        return

    if not urls:
        logger.error("No URLs found!")
        return

    # Setup authentication if provided
    cookies_file = None
    if args.email and args.password:
        cookies_file = output_dir / '.rda_cookies'
        if create_rda_cookies(args.email, args.password, cookies_file):
            logger.info("RDA authentication successful")
        else:
            logger.warning("RDA authentication failed, proceeding without cookies")
            cookies_file = None

    # Download and organize
    results = organize_downloads(urls, output_dir, args.workers, cookies_file)

    logger.info("\n" + "=" * 50)
    logger.info("DOWNLOAD COMPLETE")
    logger.info(f"Success: {results['success']}")
    logger.info(f"Failed: {results['failed']}")
    logger.info(f"Skipped: {results['skipped']}")
    logger.info(f"Output: {output_dir}")


if __name__ == '__main__':
    main()
